# Generated by Django 3.1.2 on 2020-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresponse',
            name='hash',
            field=models.CharField(max_length=8192, unique=True),
        ),
    ]
